name: Deploy Web to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Ini yang penting, ganti ke self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy and Restart
        run: |
          ssh virhan@192.168.18.163 '
            cd /home/virhan/virhanali-app
            git pull origin main
            npm install
            npm run build
            pm2 stop virhanali-app || true
            pm2 start npm --name "virhanali-app" -- start
          '