name: Deploy Web to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout kode dari repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install dependencies dan build di GitHub Actions
      - name: Install and Build
        run: |
          npm install
          npm run build

      # 3. Kirim hasil build ke VPS via SCP
      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: ./
          target: /home/virhan/virhanali-app

      # 4. Jalankan perintah di VPS untuk restart server
      - name: Restart App on VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/virhan/virhanali-app
            npm install
            npm run build
            pm2 stop virhanali-app || true
            pm2 start npm --name "virhanali-app" -- start
